server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100 MB
api:
  prefix: api/v1
LegacyDatetimeCode: false
jwt:
  expiration: 259200 # 30days
  secretKey: +oAE/EJ8bqERtsifFYrvuJdDag7USsLjiamwJ5MNZ3Y=
#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shopapp?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: root
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true